#!/bin/sh
sv start metastore || exit 1
exec $HIVE_HOME/bin/hive --service hiveserver2 --hiveconf hive.server2.authentication=NOSASL --hiveconf hive.root.logger=INFO,console > /tmp/hiveserver2.out 2> /tmp/hiveserver2.log
